### ISSUE TITLE
Deprecate older `object-omit`?

### ISSUE THREAD

**Issue by blakeembrey** [jonschlinkert/object.omit#1]
https://www.npmjs.com/package/object-omit

**Comment by jonschlinkert** [comment]
Will do. Thanks, I thought it was, but I don't see a repo for it so I must have just renamed and forgot.

**Comment by jonschlinkert** [comment]
done. thanks again

**Comment by blakeembrey** [comment]
Thanks. I confirmed by checking https://github.com/jonschlinkert/object-omit which redirects here.
